// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoW50F37es_5VjxuUl3O7XlbBl7ff06po',
    appId: '1:663267318849:web:4a3a87270923d7eee0bac0',
    messagingSenderId: '663267318849',
    projectId: 'installmentapp-1cf69',
    authDomain: 'installmentapp-1cf69.firebaseapp.com',
    databaseURL: 'https://installmentapp-1cf69-default-rtdb.firebaseio.com',
    storageBucket: 'installmentapp-1cf69.appspot.com',
    measurementId: 'G-PXG7065ZG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-u6SHv0Juw_iX4Rg5RiR3n0bDFscagJ8',
    appId: '1:663267318849:android:15885dd212d7adc7e0bac0',
    messagingSenderId: '663267318849',
    projectId: 'installmentapp-1cf69',
    databaseURL: 'https://installmentapp-1cf69-default-rtdb.firebaseio.com',
    storageBucket: 'installmentapp-1cf69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWw_tkspEt3z_ihAC-h18iFCPekB4uZ0',
    appId: '1:663267318849:ios:45f7fa9e71278f73e0bac0',
    messagingSenderId: '663267318849',
    projectId: 'installmentapp-1cf69',
    databaseURL: 'https://installmentapp-1cf69-default-rtdb.firebaseio.com',
    storageBucket: 'installmentapp-1cf69.appspot.com',
    iosBundleId: 'com.example.mentalEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiWw_tkspEt3z_ihAC-h18iFCPekB4uZ0',
    appId: '1:663267318849:ios:45f7fa9e71278f73e0bac0',
    messagingSenderId: '663267318849',
    projectId: 'installmentapp-1cf69',
    databaseURL: 'https://installmentapp-1cf69-default-rtdb.firebaseio.com',
    storageBucket: 'installmentapp-1cf69.appspot.com',
    iosBundleId: 'com.example.mentalEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu_Qi2cnr6owzIrD2lCKZktvJ_jIiLD7k',
    appId: '1:663267318849:web:aa02f307066f4631e0bac0',
    messagingSenderId: '663267318849',
    projectId: 'installmentapp-1cf69',
    authDomain: 'installmentapp-1cf69.firebaseapp.com',
    databaseURL: 'https://installmentapp-1cf69-default-rtdb.firebaseio.com',
    storageBucket: 'installmentapp-1cf69.appspot.com',
    measurementId: 'G-R6GMYGC3TJ',
  );
}
